from enum import Enum


class Buildable(Enum):
    COMPAGNIE_DE_DISTRIBUTION_DES_EAUX = 28
    COMPAGNIE_DE_DISTRIBUTION_D_ELECTRICITE = 12
    GARE_MONTPARNASSE = 5
    GARE_DU_NORD = 25
    GARE_DE_LYON = 15
    GARE_ST_LAZARE = 35
    BOULEVARD_DE_BELLEVILLE = 1
    RUE_LECOURBE = 3
    RUE_DE_VAUGIRARD = 6
    RUE_DE_COURCELLES = 8
    AVENUE_DE_LA_REPUBLIQUE = 9
    BOULEVARD_DE_LA_VILLETTE = 11
    AVENUE_DE_NEUILLY = 13
    RUE_DE_PARADIS = 14
    AVENUE_MOZART = 16
    BOULEVARD_SAINT_MICHEL = 18
    PLACE_PIGALLE = 19
    AVENUE_MATIGNON = 21
    BOULEVARD_MALESHERBES = 23
    AVENUE_HENRI_MARTIN = 24
    FAUBOURG_SAINT_HONORE = 26
    PLACE_DE_LA_BOURSE = 27
    RUE_DE_LA_FAYETTE = 29
    AVENUE_DE_BRETEUIL = 31
    AVENUE_FOCH = 32
    BOULEVARD_DES_CAPUCINES = 34
    AVENUE_DES_CHAMPS_ELYSEES = 37
    RUE_DE_LA_PAIX = 39



